import type { FormTemplateDefinition } from "./types";

const ADJECTIVE_OPTIONS = [
  "Modern",
  "Bold",
  "Trustworthy",
  "Playful",
  "Luxurious",
  "Minimal",
  "Friendly",
  "Professional",
  "Innovative",
  "Traditional",
  "Energetic",
  "Elegant",
  "Rugged",
  "Approachable",
  "Sophisticated",
  "Fun",
  "Reliable",
  "Cutting-edge",
  "Warm",
  "Authoritative",
].map((label) => ({ value: label.toLowerCase(), label }));

const COLOR_OPTIONS = [
  "Black",
  "White",
  "Navy",
  "Blue",
  "Green",
  "Red",
  "Orange",
  "Yellow",
  "Purple",
  "Gold",
  "Gray",
  "Brown",
].map((c) => ({ value: c.toLowerCase(), label: c }));

/**
 * The original brief was a static PDF questionnaire. This is a structured,
 * reusable digital form: every question is a typed field with a stable key,
 * and the packaging follow-up questions only appear when the client says the
 * logo will be used on packaging (product.md §18/§19).
 */
export const logoQuestionnaireTemplate: FormTemplateDefinition = {
  templateKey: "logo-design",
  name: "Logo Design Questionnaire",
  description:
    "Captures what the business does, who it serves, and how the logo should look and feel, before design work starts.",
  fields: [
    {
      key: "businessName",
      label: "Business name",
      type: "SHORT_TEXT",
      required: true,
    },
    {
      key: "slogan",
      label: "Slogan or tagline (if any)",
      type: "SHORT_TEXT",
      required: false,
    },
    {
      key: "companyOffering",
      label: "What does your company offer?",
      helpText: "Describe your core products or services in a few sentences.",
      type: "LONG_TEXT",
      required: true,
    },
    {
      key: "primaryMessage",
      label: "What is the single most important message the logo should support?",
      type: "LONG_TEXT",
      required: true,
    },
    {
      key: "uniqueSellingProposition",
      label: "What makes you different from competitors?",
      helpText: "Your unique selling proposition.",
      type: "LONG_TEXT",
      required: true,
    },
    {
      key: "targetMarket",
      label: "Who is your target market?",
      helpText: "Age, profession, income level, interests — whatever is relevant.",
      type: "LONG_TEXT",
      required: true,
    },
    {
      key: "logoUsage",
      label: "Where will the logo be used?",
      type: "MULTI_SELECT",
      required: true,
      options: [
        { value: "website", label: "Website" },
        { value: "business_cards", label: "Business cards" },
        { value: "signage", label: "Signage" },
        { value: "packaging", label: "Packaging" },
        { value: "merchandise", label: "Merchandise" },
        { value: "social_media", label: "Social media" },
        { value: "vehicle_branding", label: "Vehicle branding" },
        { value: "other", label: "Other" },
      ],
    },
    {
      key: "packagingType",
      label: "What type of packaging?",
      type: "SHORT_TEXT",
      required: true,
      conditionalRule: { field: "logoUsage", operator: "contains", value: "packaging" },
    },
    {
      key: "packagingDimensions",
      label: "Packaging dimensions",
      type: "SHORT_TEXT",
      required: true,
      conditionalRule: { field: "logoUsage", operator: "contains", value: "packaging" },
    },
    {
      key: "packagingPrintingMethod",
      label: "Printing method",
      type: "SHORT_TEXT",
      required: false,
      conditionalRule: { field: "logoUsage", operator: "contains", value: "packaging" },
    },
    {
      key: "packagingSubstrate",
      label: "Substrate / material",
      type: "SHORT_TEXT",
      required: false,
      conditionalRule: { field: "logoUsage", operator: "contains", value: "packaging" },
    },
    {
      key: "packagingVariantCount",
      label: "Number of packaging variants",
      type: "NUMBER",
      required: false,
      conditionalRule: { field: "logoUsage", operator: "contains", value: "packaging" },
    },
    {
      key: "preferredColors",
      label: "Preferred colors",
      type: "MULTI_SELECT",
      required: false,
      options: COLOR_OPTIONS,
    },
    {
      key: "colorsToAvoid",
      label: "Colors to avoid",
      type: "MULTI_SELECT",
      required: false,
      options: COLOR_OPTIONS,
    },
    {
      key: "colorsToAvoidNote",
      label: "Why avoid those colors?",
      type: "SHORT_TEXT",
      required: false,
      conditionalRule: { field: "colorsToAvoid", operator: "isNotEmpty" },
    },
    {
      key: "competitors",
      label: "Who are your main competitors?",
      helpText: "List 2-3 competitors and what you like or dislike about their branding.",
      type: "LONG_TEXT",
      required: true,
    },
    {
      key: "shortTermGoals",
      label: "Short-term business goals (next 12 months)",
      type: "LONG_TEXT",
      required: true,
    },
    {
      key: "longTermGoals",
      label: "Long-term business goals (3-5 years)",
      type: "LONG_TEXT",
      required: true,
    },
    {
      key: "brandAdjectives",
      label: "Choose 5-8 adjectives that describe your business",
      type: "MULTI_SELECT",
      required: true,
      minSelections: 5,
      maxSelections: 8,
      options: ADJECTIVE_OPTIONS,
    },
    {
      key: "referenceImages",
      label: "Reference logos or inspiration images",
      helpText: "Upload any logos, mood boards, or competitor marks you like (or want to avoid).",
      type: "IMAGE_UPLOAD",
      required: false,
    },
    {
      key: "additionalNotes",
      label: "Anything else the designer should know?",
      type: "LONG_TEXT",
      required: false,
    },
  ],
  conflictRules: [
    {
      fieldAKey: "preferredColors",
      fieldBKey: "colorsToAvoid",
      kind: "no-overlap",
      note: "A color appears in both \"preferred colors\" and \"colors to avoid\" — confirm with the client which one is right.",
    },
  ],
};
